ALTER TABLE character_monster_book
    ADD COLUMN IF NOT EXISTS icon VARCHAR(64) NOT NULL DEFAULT '' AFTER last_defeated_at,
    ADD COLUMN IF NOT EXISTS strong INT NOT NULL DEFAULT 0 AFTER icon,
    ADD COLUMN IF NOT EXISTS hp INT NOT NULL DEFAULT 0 AFTER strong,
    ADD COLUMN IF NOT EXISTS mp INT NOT NULL DEFAULT 0 AFTER hp,
    ADD COLUMN IF NOT EXISTS attack INT NOT NULL DEFAULT 0 AFTER mp,
    ADD COLUMN IF NOT EXISTS defense INT NOT NULL DEFAULT 0 AFTER attack,
    ADD COLUMN IF NOT EXISTS agility INT NOT NULL DEFAULT 0 AFTER defense,
    ADD COLUMN IF NOT EXISTS exp_reward INT NOT NULL DEFAULT 0 AFTER agility,
    ADD COLUMN IF NOT EXISTS gold_reward INT NOT NULL DEFAULT 0 AFTER exp_reward;

INSERT IGNORE INTO schema_migrations (version) VALUES ('095_monster_book_encounter_stats');
