package boss

func DefaultBossCatalog() []Boss {
	return []Boss{
		{
			ID:                   "king-01",
			Tier:                 1,
			Name:                 "レッドストーン・ガーディアン",
			Title:                "封印の尖兵",
			MinLevel:             15,
			HP:                   250,
			Attack:               45,
			Defense:              30,
			Agility:              20,
			ExperienceReward:     300,
			GoldReward:           500,
			DropItemIDs:          []string{"potion"},
			FirstClearExpBonus:   500,
			FirstClearGoldBonus:  1000,
			SmallMedalReward:     1,
			FirstClearMedalBonus: 1,
			DailyEntryLimit:      DefaultDailyEntryLimit,
		},
		{
			ID:                   "king-02",
			Tier:                 2,
			Name:                 "ブルーストーン・ゴーレム",
			Title:                "氷結の守護神",
			MinLevel:             25,
			HP:                   500,
			Attack:               80,
			Defense:              60,
			Agility:              35,
			ExperienceReward:     600,
			GoldReward:           1000,
			DropItemIDs:          []string{"high-potion"},
			FirstClearExpBonus:   1000,
			FirstClearGoldBonus:  2000,
			SmallMedalReward:     1,
			FirstClearMedalBonus: 1,
			DailyEntryLimit:      DefaultDailyEntryLimit,
		},
		{
			ID:                   "king-03",
			Tier:                 3,
			Name:                 "エメラルド・ワイバーン",
			Title:                "碧空の暴君",
			MinLevel:             35,
			HP:                   900,
			Attack:               130,
			Defense:              95,
			Agility:              55,
			ExperienceReward:     1000,
			GoldReward:           1800,
			DropItemIDs:          []string{"ether"},
			FirstClearExpBonus:   1500,
			FirstClearGoldBonus:  3000,
			SmallMedalReward:     1,
			FirstClearMedalBonus: 2,
			DailyEntryLimit:      DefaultDailyEntryLimit,
		},
		{
			ID:                   "king-04",
			Tier:                 4,
			Name:                 "アメジスト・ロード",
			Title:                "紫電の魔将",
			MinLevel:             45,
			HP:                   1400,
			Attack:               190,
			Defense:              140,
			Agility:              75,
			ExperienceReward:     1600,
			GoldReward:           2800,
			DropItemIDs:          []string{"high-ether"},
			FirstClearExpBonus:   2500,
			FirstClearGoldBonus:  5000,
			SmallMedalReward:     2,
			FirstClearMedalBonus: 2,
			DailyEntryLimit:      DefaultDailyEntryLimit,
		},
		{
			ID:                   "king-05",
			Tier:                 5,
			Name:                 "トパーズ・キメラ",
			Title:                "砂塵の獣王",
			MinLevel:             55,
			HP:                   2000,
			Attack:               260,
			Defense:              190,
			Agility:              100,
			ExperienceReward:     2400,
			GoldReward:           4000,
			DropItemIDs:          []string{"elixir"},
			FirstClearExpBonus:   3500,
			FirstClearGoldBonus:  7000,
			SmallMedalReward:     2,
			FirstClearMedalBonus: 3,
			DailyEntryLimit:      DefaultDailyEntryLimit,
		},
		{
			ID:                   "king-06",
			Tier:                 6,
			Name:                 "オブシディアン・ナイト",
			Title:                "黒曜の覇者",
			MinLevel:             65,
			HP:                   2800,
			Attack:               340,
			Defense:              250,
			Agility:              130,
			ExperienceReward:     3400,
			GoldReward:           5500,
			DropItemIDs:          []string{"crystal-01"},
			FirstClearExpBonus:   5000,
			FirstClearGoldBonus:  10000,
			SmallMedalReward:     2,
			FirstClearMedalBonus: 3,
			DailyEntryLimit:      DefaultDailyEntryLimit,
		},
		{
			ID:                   "king-07",
			Tier:                 7,
			Name:                 "クリスタル・ドラゴン",
			Title:                "光彩の巨竜",
			MinLevel:             75,
			HP:                   3800,
			Attack:               430,
			Defense:              320,
			Agility:              165,
			ExperienceReward:     4600,
			GoldReward:           7500,
			DropItemIDs:          []string{"crystal-02"},
			FirstClearExpBonus:   7000,
			FirstClearGoldBonus:  14000,
			SmallMedalReward:     3,
			FirstClearMedalBonus: 4,
			DailyEntryLimit:      DefaultDailyEntryLimit,
		},
		{
			ID:                   "king-08",
			Tier:                 8,
			Name:                 "ダークネス・ベヒモス",
			Title:                "深淵の殲滅者",
			MinLevel:             85,
			HP:                   5000,
			Attack:               530,
			Defense:              400,
			Agility:              200,
			ExperienceReward:     6000,
			GoldReward:           10000,
			DropItemIDs:          []string{"crystal-03"},
			FirstClearExpBonus:   9500,
			FirstClearGoldBonus:  20000,
			SmallMedalReward:     3,
			FirstClearMedalBonus: 4,
			DailyEntryLimit:      DefaultDailyEntryLimit,
		},
		{
			ID:                   "king-09",
			Tier:                 9,
			Name:                 "アビス・ルーラー",
			Title:                "黄泉の帝王",
			MinLevel:             95,
			HP:                   6500,
			Attack:               640,
			Defense:              490,
			Agility:              245,
			ExperienceReward:     8000,
			GoldReward:           14000,
			DropItemIDs:          []string{"orb-dark"},
			FirstClearExpBonus:   13000,
			FirstClearGoldBonus:  30000,
			SmallMedalReward:     4,
			FirstClearMedalBonus: 5,
			DailyEntryLimit:      DefaultDailyEntryLimit,
		},
		{
			ID:                   "king-10",
			Tier:                 10,
			Name:                 "全てを無に還す者",
			Title:                "終焉の破壊神",
			MinLevel:             99,
			HP:                   8500,
			Attack:               760,
			Defense:              590,
			Agility:              300,
			ExperienceReward:     12000,
			GoldReward:           20000,
			DropItemIDs:          []string{"orb-light"},
			FirstClearExpBonus:   20000,
			FirstClearGoldBonus:  50000,
			SmallMedalReward:     5,
			FirstClearMedalBonus: 5,
			DailyEntryLimit:      DefaultDailyEntryLimit,
		},
		{
			ID:                   "king-world",
			Tier:                 99,
			Name:                 "太古の創世神",
			Title:                "天界の守護龍神",
			MinLevel:             99,
			HP:                   12000,
			Attack:               920,
			Defense:              720,
			Agility:              360,
			ExperienceReward:     25000,
			GoldReward:           50000,
			DropItemIDs:          []string{"orb-rainbow"},
			FirstClearExpBonus:   50000,
			FirstClearGoldBonus:  100000,
			SmallMedalReward:     10,
			FirstClearMedalBonus: 20,
			DailyEntryLimit:      DefaultDailyEntryLimit,
		},
	}
}
